//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SupplierStorageWS.zofim {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServicesSoap", Namespace="http://tempuri.org/")]
    public partial class WebServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UploadFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateImageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllProductsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductsConditionedOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddAmountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNewUrlOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllCategoriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllCategoriesConditionedOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServices() {
            this.Url = global::SupplierStorageWS.Properties.Settings.Default.SupplierStorageWS_zofim_WebServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UploadFileCompletedEventHandler UploadFileCompleted;
        
        /// <remarks/>
        public event UpdateImageCompletedEventHandler UpdateImageCompleted;
        
        /// <remarks/>
        public event GetAllProductsCompletedEventHandler GetAllProductsCompleted;
        
        /// <remarks/>
        public event GetProductsConditionedCompletedEventHandler GetProductsConditionedCompleted;
        
        /// <remarks/>
        public event AddAmountCompletedEventHandler AddAmountCompleted;
        
        /// <remarks/>
        public event GetNewUrlCompletedEventHandler GetNewUrlCompleted;
        
        /// <remarks/>
        public event GetAllCategoriesCompletedEventHandler GetAllCategoriesCompleted;
        
        /// <remarks/>
        public event GetAllCategoriesConditionedCompletedEventHandler GetAllCategoriesConditionedCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UploadFile(string fileName, string contentType, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] bytes) {
            this.Invoke("UploadFile", new object[] {
                        fileName,
                        contentType,
                        bytes});
        }
        
        /// <remarks/>
        public void UploadFileAsync(string fileName, string contentType, byte[] bytes) {
            this.UploadFileAsync(fileName, contentType, bytes, null);
        }
        
        /// <remarks/>
        public void UploadFileAsync(string fileName, string contentType, byte[] bytes, object userState) {
            if ((this.UploadFileOperationCompleted == null)) {
                this.UploadFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadFileOperationCompleted);
            }
            this.InvokeAsync("UploadFile", new object[] {
                        fileName,
                        contentType,
                        bytes}, this.UploadFileOperationCompleted, userState);
        }
        
        private void OnUploadFileOperationCompleted(object arg) {
            if ((this.UploadFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadFileCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateImage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateImage(CategoryWS categoryWS) {
            this.Invoke("UpdateImage", new object[] {
                        categoryWS});
        }
        
        /// <remarks/>
        public void UpdateImageAsync(CategoryWS categoryWS) {
            this.UpdateImageAsync(categoryWS, null);
        }
        
        /// <remarks/>
        public void UpdateImageAsync(CategoryWS categoryWS, object userState) {
            if ((this.UpdateImageOperationCompleted == null)) {
                this.UpdateImageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateImageOperationCompleted);
            }
            this.InvokeAsync("UpdateImage", new object[] {
                        categoryWS}, this.UpdateImageOperationCompleted, userState);
        }
        
        private void OnUpdateImageOperationCompleted(object arg) {
            if ((this.UpdateImageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateImageCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllProducts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductWS[] GetAllProducts() {
            object[] results = this.Invoke("GetAllProducts", new object[0]);
            return ((ProductWS[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllProductsAsync() {
            this.GetAllProductsAsync(null);
        }
        
        /// <remarks/>
        public void GetAllProductsAsync(object userState) {
            if ((this.GetAllProductsOperationCompleted == null)) {
                this.GetAllProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllProductsOperationCompleted);
            }
            this.InvokeAsync("GetAllProducts", new object[0], this.GetAllProductsOperationCompleted, userState);
        }
        
        private void OnGetAllProductsOperationCompleted(object arg) {
            if ((this.GetAllProductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllProductsCompleted(this, new GetAllProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProductsConditioned", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductWS[] GetProductsConditioned(string name, bool empty) {
            object[] results = this.Invoke("GetProductsConditioned", new object[] {
                        name,
                        empty});
            return ((ProductWS[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProductsConditionedAsync(string name, bool empty) {
            this.GetProductsConditionedAsync(name, empty, null);
        }
        
        /// <remarks/>
        public void GetProductsConditionedAsync(string name, bool empty, object userState) {
            if ((this.GetProductsConditionedOperationCompleted == null)) {
                this.GetProductsConditionedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductsConditionedOperationCompleted);
            }
            this.InvokeAsync("GetProductsConditioned", new object[] {
                        name,
                        empty}, this.GetProductsConditionedOperationCompleted, userState);
        }
        
        private void OnGetProductsConditionedOperationCompleted(object arg) {
            if ((this.GetProductsConditionedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductsConditionedCompleted(this, new GetProductsConditionedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddAmount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddAmount(ProductWS product, int amount) {
            this.Invoke("AddAmount", new object[] {
                        product,
                        amount});
        }
        
        /// <remarks/>
        public void AddAmountAsync(ProductWS product, int amount) {
            this.AddAmountAsync(product, amount, null);
        }
        
        /// <remarks/>
        public void AddAmountAsync(ProductWS product, int amount, object userState) {
            if ((this.AddAmountOperationCompleted == null)) {
                this.AddAmountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddAmountOperationCompleted);
            }
            this.InvokeAsync("AddAmount", new object[] {
                        product,
                        amount}, this.AddAmountOperationCompleted, userState);
        }
        
        private void OnAddAmountOperationCompleted(object arg) {
            if ((this.AddAmountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddAmountCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNewUrl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetNewUrl(CategoryWS category) {
            object[] results = this.Invoke("GetNewUrl", new object[] {
                        category});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetNewUrlAsync(CategoryWS category) {
            this.GetNewUrlAsync(category, null);
        }
        
        /// <remarks/>
        public void GetNewUrlAsync(CategoryWS category, object userState) {
            if ((this.GetNewUrlOperationCompleted == null)) {
                this.GetNewUrlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNewUrlOperationCompleted);
            }
            this.InvokeAsync("GetNewUrl", new object[] {
                        category}, this.GetNewUrlOperationCompleted, userState);
        }
        
        private void OnGetNewUrlOperationCompleted(object arg) {
            if ((this.GetNewUrlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNewUrlCompleted(this, new GetNewUrlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllCategories", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CategoryWS[] GetAllCategories() {
            object[] results = this.Invoke("GetAllCategories", new object[0]);
            return ((CategoryWS[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCategoriesAsync() {
            this.GetAllCategoriesAsync(null);
        }
        
        /// <remarks/>
        public void GetAllCategoriesAsync(object userState) {
            if ((this.GetAllCategoriesOperationCompleted == null)) {
                this.GetAllCategoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCategoriesOperationCompleted);
            }
            this.InvokeAsync("GetAllCategories", new object[0], this.GetAllCategoriesOperationCompleted, userState);
        }
        
        private void OnGetAllCategoriesOperationCompleted(object arg) {
            if ((this.GetAllCategoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCategoriesCompleted(this, new GetAllCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllCategoriesConditioned", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CategoryWS[] GetAllCategoriesConditioned(string name) {
            object[] results = this.Invoke("GetAllCategoriesConditioned", new object[] {
                        name});
            return ((CategoryWS[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCategoriesConditionedAsync(string name) {
            this.GetAllCategoriesConditionedAsync(name, null);
        }
        
        /// <remarks/>
        public void GetAllCategoriesConditionedAsync(string name, object userState) {
            if ((this.GetAllCategoriesConditionedOperationCompleted == null)) {
                this.GetAllCategoriesConditionedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCategoriesConditionedOperationCompleted);
            }
            this.InvokeAsync("GetAllCategoriesConditioned", new object[] {
                        name}, this.GetAllCategoriesConditionedOperationCompleted, userState);
        }
        
        private void OnGetAllCategoriesConditionedOperationCompleted(object arg) {
            if ((this.GetAllCategoriesConditionedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCategoriesConditionedCompleted(this, new GetAllCategoriesConditionedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CategoryWS {
        
        private int categoryIdField;
        
        private string categoryNameField;
        
        private string categoryDescriptionField;
        
        private string categoryImageLinkField;
        
        private bool categoryActiveField;
        
        /// <remarks/>
        public int CategoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        public string CategoryName {
            get {
                return this.categoryNameField;
            }
            set {
                this.categoryNameField = value;
            }
        }
        
        /// <remarks/>
        public string CategoryDescription {
            get {
                return this.categoryDescriptionField;
            }
            set {
                this.categoryDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string CategoryImageLink {
            get {
                return this.categoryImageLinkField;
            }
            set {
                this.categoryImageLinkField = value;
            }
        }
        
        /// <remarks/>
        public bool CategoryActive {
            get {
                return this.categoryActiveField;
            }
            set {
                this.categoryActiveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SizeWS {
        
        private int sizeIDField;
        
        private string sizeNameField;
        
        /// <remarks/>
        public int SizeID {
            get {
                return this.sizeIDField;
            }
            set {
                this.sizeIDField = value;
            }
        }
        
        /// <remarks/>
        public string SizeName {
            get {
                return this.sizeNameField;
            }
            set {
                this.sizeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ColorWS {
        
        private int colorIDField;
        
        private string colorNameField;
        
        /// <remarks/>
        public int ColorID {
            get {
                return this.colorIDField;
            }
            set {
                this.colorIDField = value;
            }
        }
        
        /// <remarks/>
        public string ColorName {
            get {
                return this.colorNameField;
            }
            set {
                this.colorNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductWS {
        
        private int productIDField;
        
        private CategoryWS theCategoryField;
        
        private ColorWS theColorField;
        
        private SizeWS theSizeField;
        
        private int amountField;
        
        private string productCatColSzeStringField;
        
        /// <remarks/>
        public int ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        public CategoryWS TheCategory {
            get {
                return this.theCategoryField;
            }
            set {
                this.theCategoryField = value;
            }
        }
        
        /// <remarks/>
        public ColorWS TheColor {
            get {
                return this.theColorField;
            }
            set {
                this.theColorField = value;
            }
        }
        
        /// <remarks/>
        public SizeWS TheSize {
            get {
                return this.theSizeField;
            }
            set {
                this.theSizeField = value;
            }
        }
        
        /// <remarks/>
        public int Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string ProductCatColSzeString {
            get {
                return this.productCatColSzeStringField;
            }
            set {
                this.productCatColSzeStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void UploadFileCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void UpdateImageCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetAllProductsCompletedEventHandler(object sender, GetAllProductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductWS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductWS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetProductsConditionedCompletedEventHandler(object sender, GetProductsConditionedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductsConditionedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductsConditionedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductWS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductWS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void AddAmountCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetNewUrlCompletedEventHandler(object sender, GetNewUrlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNewUrlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNewUrlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetAllCategoriesCompletedEventHandler(object sender, GetAllCategoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CategoryWS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CategoryWS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetAllCategoriesConditionedCompletedEventHandler(object sender, GetAllCategoriesConditionedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCategoriesConditionedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCategoriesConditionedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CategoryWS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CategoryWS[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591